### ISSUE TITLE
current HTML redirect is incompatible with google search crawler

### ISSUE THREAD

**Issue by samuelcolvin** [datarobot/mkdocs-redirects#65]
I've been very confused by lots of errors I'm seeing in Google Search Console.

<img width="1394" alt="image" src="https://github.com/user-attachments/assets/1861e177-7f12-453f-8f54-1d2ba0e114e1">

The reason is that mkdocs-redirect is settings the `noindex` HTML header!

https://github.com/mkdocs/mkdocs-redirects/blob/32ccfd0ce36bcd25df66a5c58a3e1a0916f2a767/mkdocs_redirects/plugin.py#L24

I can (almost) see why someone might have thought this was a good idea. But it's definitely not!

Google is pretty [clear](https://developers.google.com/search/docs/crawling-indexing/301-redirects#metarefresh) that their crawler will respect `http-equiv="refresh"` headers, but including `<meta name="robots" content="noindex">` in the page is breaking that.

**Comment by pawamoy** [comment]
It was done here: https://github.com/mkdocs/mkdocs-redirects/pull/7. There aren't any explanation why this was considered more SEO-friendly :shrug: I'm not versed in SEO at all, but this issue looks legit so I'd be OK merging a fix if nobody is against it.

**Comment by samuelcolvin** [comment]
@XhmikosR you created #7, do you have any input?

**Comment by samuelcolvin** [comment]
Fix proposed in #66.

**Comment by samuelcolvin** [comment]
Once I released the hot fix in https://github.com/pydantic/logfire/pull/574, the page is indexable again and google is correctly following the redirect to the new URL

<img width="1412" alt="image" src="https://github.com/user-attachments/assets/360fe17a-71cc-4f96-8e8a-8fa935f6304e">

**Comment by kamilkrzyskow** [comment]
Hello 👋,
I came here after seeing the new release. At [mkdocs-nype](https://github.com/nypesap/mkdocs-nype) we also changed the `noindex`, but instead of removing it, it was changed to `index, follow` 🤔 
- https://github.com/nypesap/mkdocs-nype/blob/main/mkdocs_nype/plugins/custom_redirects/plugin.py#L33

Additionally, when looking over the Google docs the meta refresh always contained an absolute link, instead of a relative one, so this was implemented too.

Google's docs about canonical, also mention it should be used for copies / almost identical pages, so I once thought about being able to control the canonical value, but there is no real metric to measure this.

Could you please comment on that @samuelcolvin? Is removing it better than changing to `index, follow`, etc.
I guess that the answer is unknown, as SEO is a very "flaky"/delayed results sort of thing, but worth asking :v:

**Comment by samuelcolvin** [comment]
@kamilkrzyskow as you say, hard to know. 

My guess would be that removing the line is functionally same as `index, follow` - as "index" is definitely the default, and I assume the same for "follow".
